export function workbenchHtml(platformPublicUrl: string): string {
return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Atlas Workbench · 登录认证 Demo</title>
<style>
:root{font-family:Inter,system-ui,"PingFang SC",sans-serif;color:#17201f;background:#f2f6f4;--forest:#123c35;--mint:#19a881;--lime:#c8f56b;--line:#dce4e1;--muted:#687573}*{box-sizing:border-box}body{margin:0}.head{height:72px;background:var(--forest);color:#fff;display:flex;align-items:center;padding:0 28px;gap:12px}.mark{width:40px;height:40px;border-radius:12px;background:var(--lime);color:var(--forest);display:grid;place-items:center;font-weight:900}.head small{display:block;color:#9fc0b8}.page{max-width:980px;margin:auto;padding:46px 20px}.hero{display:flex;justify-content:space-between;gap:30px;align-items:center;margin-bottom:24px}.eyebrow{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:var(--mint);font-weight:900}h1{font-size:38px;margin:6px 0}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:22px;box-shadow:0 16px 45px #123c3510}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.row{display:grid;grid-template-columns:170px 1fr;gap:12px;padding:10px 0;border-bottom:1px solid #e8eeeb}.row:last-child{border:0}.row span{color:var(--muted)}button,a.button{border:1px solid var(--line);background:#fff;border-radius:9px;padding:10px 15px;font-weight:800;cursor:pointer;text-decoration:none;color:#24332f;display:inline-block}.primary{background:var(--forest)!important;border-color:var(--forest)!important;color:#fff!important}.accent{background:var(--lime)!important;border-color:var(--lime)!important;color:var(--forest)!important}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.badge{display:inline-block;padding:4px 9px;border-radius:99px;background:#eef2f1;font-size:12px;font-weight:850}.badge.ACTIVE{background:#dcf5ec;color:#08775b}.badge.PENDING_REVIEW,.badge.APPROVED{background:#fff2d8;color:#9a5a07}.error{color:#ad2635;background:#ffeaec;padding:10px;border-radius:8px}.muted{color:var(--muted)}@media(max-width:700px){.hero,.grid{display:block}.card{margin-bottom:12px}}
</style></head><body><header class="head"><div class="mark">A</div><div><strong>Atlas Workbench</strong><small>V0.1 登录与可信接入 Demo</small></div></header>
<main class="page"><section class="hero"><div><div class="eyebrow">Local execution plane</div><h1>工作台认证演示</h1><p class="muted">此 Demo 只实现企业登录、接入申请、密钥证明和机器心跳，不包含任何业务功能。</p></div><a class="button" href="${platformPublicUrl}/">公开下载页</a></section>
<div class="grid"><section class="card"><h2>本地身份</h2><div id="state">加载中…</div><div class="actions"><a id="login" class="button primary" href="/auth/login">企业账号登录</a><button id="enroll" class="accent">提交接入申请</button><button id="progress">审批后继续</button><button id="heartbeat">发送心跳</button><button id="logout">退出人员会话</button></div><p id="message" class="muted"></p></section>
<section class="card"><h2>可信边界</h2><div class="row"><span>人员身份</span><strong>Keycloak OIDC + PKCE</strong></div><div class="row"><span>本机密钥</span><strong>ES256 · AES-GCM 加密落盘</strong></div><div class="row"><span>机器认证</span><strong>private_key_jwt</strong></div><div class="row"><span>机器 Token</span><strong>仅内存 · 最长 5 分钟</strong></div></section></div></main>
<script>
const state=document.querySelector('#state'), message=document.querySelector('#message');
async function call(path,options){message.textContent='处理中…';const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options?.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||response.statusText);message.textContent='操作成功';return data}
function row(label,value){return '<div class="row"><span>'+label+'</span><strong>'+String(value||'-')+'</strong></div>'}
async function load(){try{const data=await call('/api/state');state.innerHTML=row('企业用户',data.user?.preferred_username)+row('Installation ID',data.installationId)+row('申请 ID',data.enrollmentId)+row('工作台 ID',data.workbenchId)+row('状态','<span class="badge '+data.status+'">'+data.status+'</span>')+row('最后心跳',data.lastHeartbeatAt);document.querySelector('#login').style.display=data.authenticated?'none':'inline-block'}catch(error){state.innerHTML='<p class="error">'+error.message+'</p>'}}
document.querySelector('#enroll').onclick=async()=>{try{await call('/api/enroll',{method:'POST'});await load()}catch(e){message.textContent=e.message}};
document.querySelector('#progress').onclick=async()=>{try{await call('/api/progress',{method:'POST'});await load()}catch(e){message.textContent=e.message}};
document.querySelector('#heartbeat').onclick=async()=>{try{await call('/api/heartbeat',{method:'POST'});await load()}catch(e){message.textContent=e.message}};
document.querySelector('#logout').onclick=async()=>{await call('/api/logout',{method:'POST'});location.reload()};load();
</script></body></html>`
}
