export function workbenchHtml(platformPublicUrl: string): string {
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>数字员工工作台</title>
<style>
:root{--forest:#113b34;--mint:#65b89c;--lime:#c9f56d;--line:#dce7e2;--muted:#60716d;--bg:#f5f8f6}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#20302c;font:14px/1.5 Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.head{height:72px;background:var(--forest);color:#fff;display:flex;align-items:center;padding:0 28px;gap:12px}.mark{width:40px;height:40px;border-radius:12px;background:var(--lime);color:var(--forest);display:grid;place-items:center;font-weight:900}.head small{display:block;color:#9fc0b8}
.page{max-width:1040px;margin:auto;padding:42px 20px}.hero{display:flex;justify-content:space-between;gap:30px;align-items:center;margin-bottom:24px}.eyebrow{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:var(--mint);font-weight:900}h1{font-size:36px;margin:6px 0}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:22px;box-shadow:0 16px 45px #123c3510}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.row{display:grid;grid-template-columns:170px 1fr;gap:12px;padding:10px 0;border-bottom:1px solid #e8eeeb}.row:last-child{border:0}.row span{color:var(--muted)}
button,a.button{border:1px solid var(--line);background:#fff;border-radius:9px;padding:10px 15px;font-weight:800;cursor:pointer;text-decoration:none;color:#24332f;display:inline-block}.primary{background:var(--forest)!important;border-color:var(--forest)!important;color:#fff!important}.accent{background:var(--lime)!important;border-color:var(--lime)!important;color:var(--forest)!important}.danger{background:#fff0f1!important;border-color:#efb5ba!important;color:#a32635!important}[disabled]{opacity:.55;cursor:not-allowed}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.badge{display:inline-block;padding:4px 10px;border-radius:99px;background:#eef2f1;font-size:12px;font-weight:850}.badge.ACTIVE{background:#dcf5ec;color:#08775b}.badge.PENDING_REVIEW,.badge.APPROVED,.badge.COMPLETED{background:#fff2d8;color:#9a5a07}.badge.REJECTED,.badge.ERROR,.badge.REVOKED{background:#ffe7ea;color:#ad2635}.notice{margin-top:16px;padding:12px 14px;border-radius:10px;background:#f3f7f5;border:1px solid var(--line)}.notice strong{display:block;margin-bottom:4px}.error{color:#ad2635}.muted{color:var(--muted)}@media(max-width:760px){.hero,.grid{display:block}.card{margin-bottom:12px}.row{grid-template-columns:1fr}}
</style></head><body>
<header class="head"><div class="mark">数</div><div><strong>数字员工工作台</strong><small>企业登录与可信接入</small></div></header>
<main class="page">
  <section class="hero"><div><div class="eyebrow">Local execution plane</div><h1>工作台接入状态</h1><p class="muted">登录后将自动提交接入申请；审批通过并完成密钥证明后，才可以使用工作台能力。</p></div><a class="button" href="${platformPublicUrl}/">返回管理平台</a></section>
  <div class="grid">
    <section class="card"><h2>接入状态</h2><div id="state">加载中…</div><div id="actions" class="actions"></div><p id="message" class="muted"></p></section>
    <section class="card"><h2>安全边界</h2><div class="row"><span>人员认证</span><strong>Keycloak OIDC + PKCE</strong></div><div class="row"><span>审批控制</span><strong>按组织路径授权管理员</strong></div><div class="row"><span>本机密钥</span><strong>ES256 · AES-GCM 加密落盘</strong></div><div class="row"><span>机器认证</span><strong>private_key_jwt + Bearer Token</strong></div></section>
  </div>
</main>
<script>
const stateNode=document.querySelector('#state'), actionsNode=document.querySelector('#actions'), messageNode=document.querySelector('#message');
let pollTimer;
function esc(value){return String(value??'-').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function row(label,value){return '<div class="row"><span>'+label+'</span><strong>'+value+'</strong></div>'}
function statusLabel(status){return {NEW:'未提交',PENDING_REVIEW:'待审批',APPROVED:'已批准待激活',COMPLETED:'已完成注册',ACTIVE:'已激活',REJECTED:'已拒绝',REVOKED:'已吊销',ERROR:'提交失败'}[status]||status}
async function call(path,options={}){messageNode.textContent='处理中…';const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||response.statusText);messageNode.textContent='操作成功';return data}
function action(id,label,mode='',hidden=false){return hidden?'':'<button id="'+id+'" class="'+mode+'">'+label+'</button>'}
async function refresh(){const data=await call('/api/state');const locked=['NEW','PENDING_REVIEW','APPROVED','COMPLETED','REJECTED','ERROR'].includes(data.status);stateNode.innerHTML=row('企业用户',data.authenticated?esc(data.user?.name||data.user?.preferred_username||'已登录'):'未登录')+row('Installation ID',esc(data.installationId))+row('申请 ID',esc(data.enrollmentId))+row('工作台 ID',esc(data.workbenchId))+row('状态','<span class="badge '+esc(data.status)+'">'+esc(statusLabel(data.status))+'</span>')+row('最后心跳',esc(data.lastHeartbeatAt));if(data.rejectionReason)stateNode.innerHTML+='<div class="notice error"><strong>拒绝原因</strong>'+esc(data.rejectionReason)+'</div>';if(data.error)stateNode.innerHTML+='<div class="notice error"><strong>申请异常</strong>'+esc(data.error)+'</div>';if(!data.authenticated)stateNode.innerHTML+='<div class="notice"><strong>请先登录</strong>工作台需要通过企业账号完成 Keycloak 认证。</div>';else if(locked)stateNode.innerHTML+='<div class="notice"><strong>能力已锁定</strong>接入申请审批通过并完成本机激活后，才可发送心跳和使用其他工作台能力。</div>';
actionsNode.innerHTML=action('login','企业账号登录','primary',data.authenticated)+action('enroll','重新提交接入申请','accent',!data.authenticated||!['NEW','REJECTED','ERROR'].includes(data.status))+action('heartbeat','发送工作台心跳','',!data.authenticated||data.status!=='ACTIVE')+action('reset','重置申请状态','danger',!data.authenticated||!['REJECTED','ERROR'].includes(data.status))+action('logout','退出登录','danger',!data.authenticated);
document.querySelector('#login')?.addEventListener('click',()=>location.href='/auth/login');document.querySelector('#enroll')?.addEventListener('click',async()=>{await call('/api/enroll',{method:'POST'});refresh()});document.querySelector('#heartbeat')?.addEventListener('click',async()=>{await call('/api/heartbeat',{method:'POST'});refresh()});document.querySelector('#reset')?.addEventListener('click',async()=>{await call('/api/reset',{method:'POST'});refresh()});document.querySelector('#logout')?.addEventListener('click',async()=>{await call('/api/logout',{method:'POST'});location.reload()});
clearInterval(pollTimer);if(data.authenticated&&['PENDING_REVIEW','APPROVED'].includes(data.status))pollTimer=setInterval(async()=>{try{await call('/api/progress',{method:'POST'});await refresh()}catch(error){messageNode.textContent=error.message}},5000)}
refresh().catch(error=>{stateNode.innerHTML='<p class="error">'+esc(error.message)+'</p>';messageNode.textContent=''});
</script></body></html>`
}
