import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { createClaudeCodeAdapter } from '../src/adapters/claude-code/index'
import { createQoderAdapter } from '../src/adapters/qoder/index'

// HOME 用真实 tmpdir 路径（plan 草稿的 C:/staff/... 为假路径——回退档身份拷贝源须真实存在）
const HOME = mkdtempSync(join(tmpdir(), 'wb-launch-home-'))
const WORK = mkdtempSync(join(tmpdir(), 'wb-launch-'))

// 回退档前置：HOME/config/AGENTS.md 身份文件（adapt 产物替身——launch 回退档全文拷贝源）
mkdirSync(join(HOME, 'config'), { recursive: true })
writeFileSync(join(HOME, 'config', 'AGENTS.md'), '# 身份', 'utf8')

const input = {
  deployment: { base: 'claude-code' as const, home: HOME, employee_id: 'dev-lite' },
  workdir: WORK, prompt: '修复登录页 bug\n按 TDD 走',
  permission: 'acceptEdits', model: 'claude-sonnet-5', effort: 'high',
}

describe('launch()（设计 §4.3；LaunchSpec 纯构造 + prompt 文件中转）', () => {
  it('CC：env CLAUDE_CONFIG_DIR 指向 home/config；cwd=workdir；args 带 -p 与 prompt 全文 + permission/model 旗标', async () => {
    const spec = await createClaudeCodeAdapter().launch(input)
    expect(spec.command).toBe('claude')
    expect(spec.env.CLAUDE_CONFIG_DIR).toBe(join(HOME, 'config'))
    expect(spec.cwd).toBe(WORK)
    expect(spec.args).toContain('-p')
    expect(spec.args).toContain('修复登录页 bug\n按 TDD 走')   // args 数组直传不经 shell——多行安全（四坑坑1 免疫）
    expect(spec.args).toContain('--permission-mode')
    expect(spec.args).toContain('--model')
  })

  it('prompt 文件中转：workdir/.devzero/ 下落盘 prompt 文件且内容=全文（观测/审计；LaunchSpec.promptFile 回指）', async () => {
    const spec = await createClaudeCodeAdapter().launch(input)
    expect(spec.promptFile).toBeDefined()
    expect(existsSync(spec.promptFile!)).toBe(true)
    expect(readFileSync(spec.promptFile!, 'utf8')).toContain('修复登录页 bug')
    expect(spec.promptFile!.startsWith(join(WORK, '.devzero'))).toBe(true)
  })

  it('Qoder：config 域走 --config-dir 旗标（非 env）；qodercli 命令', async () => {
    const spec = await createQoderAdapter().launch({ ...input, deployment: { ...input.deployment, base: 'qoder' } })
    expect(spec.command).toBe('qodercli')
    expect(spec.args).toContain('--config-dir')
    expect(spec.args).toContain(join(HOME, 'config'))
    expect(spec.env.CLAUDE_CONFIG_DIR).toBeUndefined()
  })

  it('project-file 回退档：不带 config 注入，身份薄壳落 workdir（AGENTS.md + 溯源注释）', async () => {
    const adapter = createQoderAdapter()
    // profile 是模块级共享常量——用例内改值必须还原，防跨用例污染（adapter 各自新建但共享同一 profile 对象）
    const original = adapter.profile.identity_anchor
    adapter.profile.identity_anchor = 'project-file'
    try {
      const spec = await adapter.launch({ ...input, deployment: { ...input.deployment, base: 'qoder' } })
      expect(spec.args).not.toContain('--config-dir')
      const shell = readFileSync(join(WORK, 'AGENTS.md'), 'utf8')
      expect(shell).toContain('generated by devzero from dev-lite@')
    } finally {
      adapter.profile.identity_anchor = original
    }
  })

  it('可选参数缺省：不带 permission/model/effort 旗标', async () => {
    const spec = await createClaudeCodeAdapter().launch({ ...input, permission: undefined, model: undefined, effort: undefined })
    expect(spec.args).not.toContain('--permission-mode')
    expect(spec.args).not.toContain('--model')
  })
})
