/**
 * AGENTS.md 渲染器（Task 9 / B4）：六段式双变体 + 物料快照对齐测试。
 *
 * 数据源：builtinTemplates 内存 Record（不依赖 fs，覆盖 codegen 产物）。
 * 测试对 7 个模板逐个断言：renderAgentsMd(解析后的 manifest, skills 描述清单) === builtinTemplates['<tplId>/AGENTS.md']。
 *
 * skills 描述清单从模板 skills 目录的 SKILL.md frontmatter 解析（测试内做）。
 */
import { describe, it, expect } from 'vitest'
import yaml from 'js-yaml'
import { manifestSchema, skillFrontmatterSchema } from '@devzero/shared-protocol'
import type { Manifest } from '@devzero/shared-protocol'
import { builtinTemplates } from '../src/assets/templates.gen'
import { renderAgentsMd } from '../src/employees/renderer'

const TEMPLATE_IDS = [
  'dev-engineer',
  'req-clarifier',
  'reviewer-expert',
  'sec-code',
  'sec-compliance',
  'sec-design',
  'sys-engineer',
] as const

/** 解析 builtinTemplates['<tplId>/manifest.yml'] → Manifest（schema parse） */
function parseManifest(tplId: string): Manifest {
  const text = builtinTemplates[`${tplId}/manifest.yml`]
  if (text === undefined) throw new Error(`manifest.yml 缺失：${tplId}`)
  const doc = yaml.load(text)
  const r = manifestSchema.parse(doc)
  return r as Manifest
}

/** 解析 builtinTemplates['<tplId>/skills/<name>/SKILL.md'] frontmatter description */
function parseSkillDescription(tplId: string, skillName: string): string {
  const text = builtinTemplates[`${tplId}/skills/${skillName}/SKILL.md`]
  if (text === undefined) return ''
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!m) return ''
  const fmText = m[1]
  if (!fmText) return ''
  let doc: unknown
  try {
    doc = yaml.load(fmText)
  } catch {
    return ''
  }
  if (typeof doc !== 'object' || doc === null) return ''
  const r = skillFrontmatterSchema.safeParse(doc)
  if (!r.success) {
    const desc = (doc as Record<string, unknown>).description
    return typeof desc === 'string' ? desc : ''
  }
  return r.data.description
}

/** 组装某模板的 skills 描述清单：[{name, version, description}, ...] */
function buildSkillsList(tplId: string, manifest: Manifest): Array<{ name: string; version: string; description: string }> {
  return manifest.skills.map((s) => ({
    name: s.name,
    version: s.version,
    description: parseSkillDescription(tplId, s.name),
  }))
}

describe('renderAgentsMd — 7 模板物料快照对齐', () => {
  for (const tplId of TEMPLATE_IDS) {
    it(`${tplId}: renderAgentsMd(manifest, skills) === builtinTemplates['${tplId}/AGENTS.md']`, () => {
      const manifest = parseManifest(tplId)
      const skills = buildSkillsList(tplId, manifest)
      const rendered = renderAgentsMd(manifest, skills)
      const expected = builtinTemplates[`${tplId}/AGENTS.md`] ?? ''
      // 物料为手写——若不一致：渲染器逻辑错改渲染器；个别物料文案漂移改物料 AGENTS.md
      expect(rendered).toBe(expected)
    })
  }
})

describe('renderAgentsMd — 结构断言（基于 dev-engineer）', () => {
  const manifest = parseManifest('dev-engineer')
  const skills = buildSkillsList('dev-engineer', manifest)
  const rendered = renderAgentsMd(manifest, skills)

  it('首行 generated-by HTML 注释（id@version）', () => {
    expect(rendered.startsWith('<!-- generated by devzero from template dev-engineer@0.1.0; do not edit by hand -->')).toBe(true)
  })

  it('标题 # {display}（{id}）', () => {
    expect(rendered).toContain('# 开发工程师（dev-engineer）')
  })

  it('六段固定标题文案齐全', () => {
    expect(rendered).toContain('## 我是谁')
    expect(rendered).toContain('## 我的原则')
    expect(rendered).toContain('## 我的能力')
    expect(rendered).toContain('## 我的边界（软约束）')
    expect(rendered).toContain('## 我的工作方式')
    expect(rendered).toContain('## 协同工作纪律')
  })

  it('「我是谁」段：{role}。本角色为用户配置的数字员工岗位。', () => {
    expect(rendered).toContain('数字员工·开发岗。本角色为用户配置的数字员工岗位。')
  })

  it('「我的能力」技能清单行：name@version 列表 + 按需加载提示', () => {
    expect(rendered).toContain(
      '（技能清单：tdd-methodology@1.0.0 frontend-design@1.0.0 secure-coding@1.0.0 writing-plans@1.0.0 verification-before-completion@1.0.0 —— 按需加载对应 SKILL.md）',
    )
  })

  it('「我的边界」末尾硬约束引用块', () => {
    expect(rendered).toContain('> 硬约束由工作台编译的 hooks 与 CQO 双重执行，越界操作会被阻断。')
  })

  it('「我的工作方式」使用深度行（usage_modes / 分隔）', () => {
    expect(rendered).toContain('使用深度：裸用 / +方法论 / +流程 / +编排')
  })

  it('flow-owner 末段「干完必报三件套」（kind 分派）', () => {
    expect(rendered).toContain('**干完必报三件套**')
    expect(rendered).toContain('`engine_advance`')
    expect(rendered).toContain('`engine_handoff_write`')
    expect(rendered).toContain('`engine_dispatch_done`')
  })

  it('共用铁律尾句「引擎工具不可用 = 工作台未运行」', () => {
    expect(rendered).toContain('**引擎工具不可用 = 工作台未运行**')
  })
})

describe('renderAgentsMd — callee kind 双变体（reviewer-expert）', () => {
  const manifest = parseManifest('reviewer-expert')
  const skills = buildSkillsList('reviewer-expert', manifest)
  const rendered = renderAgentsMd(manifest, skills)

  it('callee 末段「回函三件套」（kind 分派）', () => {
    expect(rendered).toContain('**回函三件套**')
    expect(rendered).toContain('`engine_record_gate`')
    expect(rendered).toContain('`engine_handoff_write`')
    expect(rendered).toContain('`engine_dispatch_done`')
  })

  it('callee 不含干完必报三件套', () => {
    expect(rendered).not.toContain('干完必报三件套')
  })
})

describe('renderAgentsMd — 无 skills 模板技能清单行（占位文案）', () => {
  // 构造空 skills 的合成 manifest（builtin 模板现已全部有 skills——用合成 manifest 测占位分支）
  const emptySkillsManifest: Manifest = {
    ...parseManifest('sec-compliance'),
    skills: [],
  }
  const rendered = renderAgentsMd(emptySkillsManifest, [])

  it('空 skills 时技能清单行用占位文案', () => {
    expect(rendered).toContain(
      '（技能清单：本员工暂无内置技能（如需扩展请编辑 manifest.skills 后重渲染））',
    )
  })
})
