import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { beforeEach, describe, expect, it } from 'vitest'
import { createDeploymentRegistry } from '../src/installs/registry/registry'
import { fixturePackageDir, parsePackage } from '../src/installs/spec/parser'
import { createClaudeCodeAdapter } from '../src/adapters/claude-code/index'
import { executeInstall, recoverInterrupted } from '../src/installs/executor/execute'
import type { ExecuteInput } from '../src/installs/executor/execute'

let scratch: string

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'wb-exec-'))
  // auth 凭证源（CC adapter 重构后 plan 含 __auth__/.credentials.json 虚拟源落位——成功链前置）
  mkdirSync(join(scratch, 'user-cc'), { recursive: true })
  writeFileSync(join(scratch, 'user-cc', '.credentials.json'), '{}', 'utf8')
})

const PROBE = { present: true, version: '2.1.245' }

function makeInput(over: Partial<ExecuteInput> = {}): ExecuteInput {
  return {
    spec: undefined as never, adapter: createClaudeCodeAdapter(),
    packageRoot: fixturePackageDir(),
    registry: createDeploymentRegistry(join(scratch, 'registry.json')),
    registryFile: join(scratch, 'registry.json'),
    home: join(scratch, 'digital-staff', 'claude-code', 'dev-lite'),
    baseVersion: '2.1.245', probe: PROBE,
    authSourceDir: join(scratch, 'user-cc'),
    ...over,
  }
}

describe('executeInstall（事务八条——设计 §6）', () => {
  it('成功链：home/config 域产物齐备（身份文件含溯源注释/skills/hooks merge 带 _devzero 标记）+ registry installed + manifest 落盘', async () => {
    const input = makeInput({ spec: await parsePackage(fixturePackageDir()) })
    const out = executeInstall(input)
    expect(out.result).toBe('success')
    const cfg = join(input.home, 'config')
    const identity = readFileSync(join(cfg, 'CLAUDE.md'), 'utf8')
    expect(identity).toContain('# 我是谁')
    expect(identity).toContain('generated by devzero from dev-lite@0.1.0/AGENTS.md')
    expect(existsSync(join(cfg, 'skills', 'tdd-methodology', 'SKILL.md'))).toBe(true)
    const settings = JSON.parse(readFileSync(join(cfg, 'settings.json'), 'utf8'))
    expect(settings.hooks.PreToolUse[0]._devzero).toBe('dev-lite')
    expect(existsSync(join(input.home, '.devzero-manifest.json'))).toBe(true)
    expect(input.registry.find('claude-code', 'dev-lite')?.status).toBe('installed')
  })

  it('幂等：同输入重跑 → unchanged 且不重写产物（mtime 不变）', async () => {
    const spec = await parsePackage(fixturePackageDir())
    const input = makeInput({ spec })
    executeInstall(input)
    const mtimeBefore = readFileSync(join(input.home, 'config', 'CLAUDE.md'), 'utf8')
    const out2 = executeInstall(input)
    expect(out2.result).toBe('unchanged')
    expect(readFileSync(join(input.home, 'config', 'CLAUDE.md'), 'utf8')).toBe(mtimeBefore)
  })

  it('失败注入回滚：包缺 skills 目录 → rolled-back，域内无残留、registry 标 broken、报告级错误对象含 code/phase', async () => {
    const spec = await parsePackage(fixturePackageDir())
    const brokenPkg = join(scratch, 'broken-pkg')
    mkdirSync(brokenPkg, { recursive: true })
    writeFileSync(join(brokenPkg, 'manifest.yml'), readFileSync(join(fixturePackageDir(), 'manifest.yml')))
    writeFileSync(join(brokenPkg, 'AGENTS.md'), readFileSync(join(fixturePackageDir(), 'AGENTS.md')))
    // skills/ 与 hooks/ 均缺失 → 执行中失败
    const input = makeInput({ spec, packageRoot: brokenPkg })
    const out = executeInstall(input)
    expect(out.result).toBe('rolled-back')
    expect(out.error?.code).toBe('INSTALL_SOURCE_MISSING')
    expect(out.error?.phase).toBe('execute')
    expect(existsSync(join(input.home, 'config'))).toBe(false)
    expect(input.registry.find('claude-code', 'dev-lite')?.status).toBe('broken')
  })

  it('blocked（版本断言不符）→ failed：不建域、registry 不留行、错误一等公民', async () => {
    const spec = await parsePackage(fixturePackageDir())
    const input = makeInput({ spec, probe: { present: true, version: '1.0.0' } })
    const out = executeInstall(input)
    expect(out.result).toBe('failed')
    expect(out.error?.code).toBe('BASE_VERSION_UNSUPPORTED')
    expect(existsSync(input.home)).toBe(false)
    expect(input.registry.find('claude-code', 'dev-lite')).toBeUndefined()
  })

  it('auth env-token 分档（设计 §5.1，M2 实测）：凭证文件缺失 + env 有 token -> 零置备降级成功（环境继承）', async () => {
    const envBackup = process.env.ANTHROPIC_AUTH_TOKEN
    process.env.ANTHROPIC_AUTH_TOKEN = 'wb-test-env-token'
    try {
      const emptyAuthDir = join(scratch, 'empty-cc')
      mkdirSync(emptyAuthDir, { recursive: true }) // 目录在但无 .credentials.json
      const input = makeInput({ spec: await parsePackage(fixturePackageDir()), authSourceDir: emptyAuthDir })
      const out = executeInstall(input)
      expect(out.result).toBe('success')
      expect(existsSync(join(input.home, 'config', '.credentials.json'))).toBe(false) // 零置备
      expect(input.registry.find('claude-code', 'dev-lite')?.status).toBe('installed')
    } finally {
      if (envBackup === undefined) delete process.env.ANTHROPIC_AUTH_TOKEN
      else process.env.ANTHROPIC_AUTH_TOKEN = envBackup
    }
  })

  it('auth 双缺才阻塞：无凭证文件且 env 无 token -> INSTALL_AUTH_SOURCE_MISSING 回滚', async () => {
    const envBackup = process.env.ANTHROPIC_AUTH_TOKEN
    delete process.env.ANTHROPIC_AUTH_TOKEN
    try {
      const emptyAuthDir = join(scratch, 'empty-cc2')
      mkdirSync(emptyAuthDir, { recursive: true })
      const input = makeInput({ spec: await parsePackage(fixturePackageDir()), authSourceDir: emptyAuthDir })
      const out = executeInstall(input)
      expect(out.result).toBe('rolled-back')
      expect(out.error?.code).toBe('INSTALL_AUTH_SOURCE_MISSING')
    } finally {
      if (envBackup === undefined) delete process.env.ANTHROPIC_AUTH_TOKEN
      else process.env.ANTHROPIC_AUTH_TOKEN = envBackup
    }
  })

  it('崩溃恢复：installing 残行 + 完整域 → 补转 installed；不完整 → broken（kill -9 模拟）', async () => {
    const spec = await parsePackage(fixturePackageDir())
    const input = makeInput({ spec })
    // 模拟 kill -9：手工造 installing 行 + 半成品域（只有 config/ 无 manifest）
    mkdirSync(join(input.home, 'config'), { recursive: true })
    writeFileSync(join(input.home, 'config', 'CLAUDE.md'), 'half', 'utf8')
    input.registry.upsert({
      employee_id: 'dev-lite', spec_version: '0.1.0', base: 'claude-code',
      home: input.home, status: 'installing',
      identity_anchor: 'config-domain', base_version: '2.1.245',
      installed_at: new Date().toISOString(), last_launch_at: null,
      manifest_path: join(input.home, '.devzero-manifest.json'),
    })
    const r1 = recoverInterrupted(input.registry)
    expect(r1.broken).toContain('claude-code:dev-lite')
    expect(input.registry.find('claude-code', 'dev-lite')?.status).toBe('broken')
    // 幂等自愈：重装成功后转 installed
    const out = executeInstall(input)
    expect(out.result).toBe('success')
    expect(input.registry.find('claude-code', 'dev-lite')?.status).toBe('installed')
  })

  it('升级不触 memory：spec.version 变化重装 → memory/sessions 用户资产原样保留（B-03 验收口径）', async () => {
    const spec = await parsePackage(fixturePackageDir())
    const input = makeInput({ spec })
    expect(executeInstall(input).result).toBe('success')
    writeFileSync(join(input.home, 'memory', 'notes.md'), '用户跨会话记忆', 'utf8')
    mkdirSync(join(input.home, 'sessions'), { recursive: true })
    writeFileSync(join(input.home, 'sessions', 's1.json'), '{"workdir":"x"}', 'utf8')

    const upgraded = { ...spec, version: '0.2.0' }
    const out2 = executeInstall(makeInput({ spec: upgraded }))
    expect(out2.result).toBe('success')
    expect(readFileSync(join(input.home, 'memory', 'notes.md'), 'utf8')).toBe('用户跨会话记忆')
    expect(readFileSync(join(input.home, 'sessions', 's1.json'), 'utf8')).toBe('{"workdir":"x"}')
    expect(input.registry.find('claude-code', 'dev-lite')?.spec_version).toBe('0.2.0')
  })
})
